    name: GitHub Classroom Workflow

    on: [push]

    jobs:
      build:
        name: Autograding
        runs-on: ubuntu-latest
        env:
          DOTNET_CLI_HOME: /tmp
        steps:
          - uses: actions/checkout@v2
          - name: Setup .NET 3.1.x
            uses: actions/setup-dotnet@v1.7.2
            with:
              # Semantic version range syntax or exact version of a dotnet version
              dotnet-version: '3.1.x'
          - name: Restore dependencies
            run: dotnet restore
          - name: Build
            run: dotnet build --configuration Release --no-restore
          - uses: mariosky/autograding@v1.0.2



